
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nadadoux
 */
public class Page6_BidDetails extends javax.swing.JFrame {
       boolean first=true ;  
          private static Timer ourtimer;
   private static TimerTask ourtask;
   private static gui ourgui;
     Task k=new Task();
       
       
    public Page6_BidDetails(String ProductName,String UserName) {
        initComponents();
        this.setSize(900, 900);
        String Productname=ProductName ; 
        findProductUserDetails(Productname,UserName);
    }
    
    public void findProductUserDetails(String ProductName,String UserName)
    {
        
        Connection con = null; //manages connection
         Statement st = null; // query statement
         ResultSet rs = null; // manages results
              int itemID=0   ;  
              String itemname="";
              int startingPrice=0;
              String ProductDescription="";
     try 
     {
            con =DriverManager.getConnection("jdbc:mysql://localhost/auction","root","");
            st= con.createStatement();	
            rs = st.executeQuery("select * from item_information where item_name='" + ProductName + "'");
            while(rs.next())
            {
                 System.out.println(itemID+" "+itemname+" ");
                itemID = rs.getInt("Item_ID");
                itemname=rs.getString("item_name");
                startingPrice = rs.getInt("Starting_price");
                ProductDescription=rs.getString("itemDescription");
            }
     }
        catch ( Exception e )  
       {                                                                  
         e.printStackTrace();
      }
       
     finally
     {
         try
         {
          rs.close();                                      
          st.close();                                      
          con.close(); 
          
      }
      catch ( Exception e )                                
      {                                                                  
         e.printStackTrace();
      }                                                    
     }
     String startingPRice=Integer.toString(startingPrice) ; 
     String itemiD=Integer.toString(itemID) ; 
      jTextField13.setText(itemname);
      jTextField12.setText(startingPRice);
      jTextField19.setText(ProductDescription);
      jTextField14.setText(itemiD);
      jTextField16.setText(startingPRice);
      jTextField20.setText(UserName);
     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        jButton10.setText("Login");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jTextField4.setText("Product Category:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.gif"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 0, 200, 65);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/J-GRAS-BUGLE.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 80, 270, 110);

        jTextField5.setText("Product Name: ");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(10, 210, 130, 30);

        jTextField1.setText("Product Model:");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(260, 210, 130, 30);

        jTextField2.setText("Starting Price: ");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(10, 290, 130, 30);

        jTextField3.setText("Highest Bid: ");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(260, 290, 130, 30);

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField12);
        jTextField12.setBounds(10, 330, 170, 30);

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField13);
        jTextField13.setBounds(10, 250, 170, 30);
        getContentPane().add(jTextField14);
        jTextField14.setBounds(260, 250, 170, 30);
        getContentPane().add(jTextField16);
        jTextField16.setBounds(260, 330, 170, 30);

        jTextField7.setText("Product Description:");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(10, 530, 130, 30);

        jTextField9.setText("Current Bid Winner: ");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(10, 450, 130, 30);
        getContentPane().add(jTextField19);
        jTextField19.setBounds(10, 570, 180, 90);

        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField20);
        jTextField20.setBounds(10, 490, 170, 30);

        jButton1.setText("Bid On Product");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 610, 130, 50);

        jButton2.setText("Ramy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(243, 460, 80, 50);

        jButton3.setText("Mina");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(240, 530, 80, 50);

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11);
        jTextField11.setBounds(330, 460, 100, 50);
        getContentPane().add(jTextField21);
        jTextField21.setBounds(330, 530, 100, 50);

        jButton4.setText("AuctionTime");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(100, 373, 210, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Page2_Login s = new Page2_Login();
        s.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          
      
       
        if(first)
        {
          int ProductPrice =Integer.parseInt(jTextField12.getText());
          String User="Ramy";
          k.announceWinner(User);
          int ProductPriceUpdate =Integer.parseInt(jTextField11.getText());
          int total =ProductPrice+ProductPriceUpdate ;
          String Total=Integer.toString(total) ; 
          jTextField16.setText(Total);
          jTextField20.setText(User);
          first=false ; 
        }
        else
        {
          int ProductPrice =Integer.parseInt(jTextField16.getText());
          String User="Ramy";
          k.announceWinner(User);
          int ProductPriceUpdate =Integer.parseInt(jTextField11.getText());
          int total =ProductPrice+ProductPriceUpdate ;
          String Total=Integer.toString(total) ; 
          jTextField16.setText(Total);
          jTextField20.setText(User);      
        }
          
          
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
    
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(first)
        {
          int ProductPrice =Integer.parseInt(jTextField12.getText());
          String User="Mina";
          k.announceWinner(User);
          int ProductPriceUpdate =Integer.parseInt(jTextField11.getText());
          int total =ProductPrice+ProductPriceUpdate ;
          String Total=Integer.toString(total) ; 
          jTextField16.setText(Total);
          jTextField20.setText(User);
          first=false ; 
        }
        else
        {
          int ProductPrice =Integer.parseInt(jTextField16.getText());
          String User="Mina";
          k.announceWinner(User);
          int ProductPriceUpdate =Integer.parseInt(jTextField21.getText());
          int total =ProductPrice+ProductPriceUpdate ;
          String Total=Integer.toString(total) ; 
          jTextField16.setText(Total);
          jTextField20.setText(User);      
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed
public static gui getGui()
    {
        return ourgui;
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        ourtimer = new Timer();
        ourtask = new Task() ;
        ourgui = new gui();
        ourtimer.scheduleAtFixedRate(ourtask, 1000, 1000);
         
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page6_BidDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page6_BidDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page6_BidDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page6_BidDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
