
import java.sql.DriverManager;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nadadoux
 */
public class Page5_AddProduct extends javax.swing.JFrame {

    /**
     * Creates new form Page5_AddProduct
     */
    public Page5_AddProduct() {
        initComponents();
        this.setSize(600, 600);
    }
    public void addProduct(String ProductName,int startingprice,String Description)
    {
        Connection con = null; //manages connection
         Statement st = null; // query statement
         ResultSet rs = null; // manages results
                        
        
     try 
      {
            //Connect to your ODBC
            con =DriverManager.getConnection("jdbc:mysql://localhost/auction","root","");
           // create Statement for querying database
           st= con.createStatement();
           PreparedStatement ps = con.prepareStatement("insert into item_information(item_name,Starting_price,Image,itemDescription) values (?,?,?,?)");
           ps.setString(1, ProductName);
           ps.setInt(2, startingprice);
           ps.setInt(3, 0);
           ps.setString(4, Description);
            
           ps.executeUpdate(); 
       //    System.out.println ("\n After insert:");
           
           JOptionPane.showMessageDialog(null, "Product added successfully");
           boolean choice=true ; 
           if(choice)
           {
           Page7_Products s=new  Page7_Products() ; 
              s.setVisible(true);
           }
           rs = st.executeQuery("Select * From item_information");			
            while(rs.next())
            {
                String name = rs.getString("item_name");
                int StartingPrice = rs.getInt("Starting_price");
                this.setVisible(false);
            }

    }
      catch ( Exception e )  
       {                                                                  
         e.printStackTrace();
      }
       
     finally
     {
         try
         {
          rs.close();                                      
          st.close();                                      
          con.close(); 
          
      }
      catch ( Exception e )                                
      {                                                                  
         e.printStackTrace();
      }                                                    
     }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg - Copy (3).jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.gif"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 0, 200, 65);

        jTextField1.setText("Product Name:");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(30, 110, 130, 30);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(200, 110, 220, 30);

        jTextField2.setText("Product Model:");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(30, 160, 130, 30);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(200, 160, 220, 30);

        jTextField3.setText("Starting Price:");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(30, 210, 130, 30);

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(200, 210, 220, 30);

        jTextField6.setText("Product Description:");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(30, 260, 130, 30);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(200, 260, 220, 70);

        jTextField4.setText("Product Category:");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(30, 350, 130, 30);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(200, 350, 220, 30);

        jButton1.setText("Add Product");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 400, 100, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg - Copy (4).jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 70, 1030, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        String Name =jTextField7.getText(); 
        int starting=Integer.parseInt(jTextField9.getText() ); 
        String description=jTextField10.getText(); 
        addProduct(Name,starting,description) ; 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page5_AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page5_AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page5_AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page5_AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page5_AddProduct().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
